### ISSUE TITLE
Can't add Stripe payment provider

### ISSUE THREAD

**Issue by CyberiaResurrection** [aimeoscom/ai-payments#2]
I've added ai-payments to my existing aimeos-laravel install, and am trying to set up Stripe as a payment service.

Selected status of enabled, type of Payment, Code is Stripe, Provider is Stripe, Label is Stripe, position is 0, I add the apiKey etc as requested, then click save.

In the dialog that comes up, I get:
Argument 1 passed to Controller_ExtJS_Abstract::_transformValues() must be an instance of stdClass, array given, called in /var/www/html/BCS/vendor/aimeos/aimeos-core/controller/extjs/src/Controller/ExtJS/Service/Default.php on line 54 and defined

I guess this means that it didn't save and I don't have an option to let people pay via Stripe?

**Comment by aimeos** [comment]
We did some changes a week ago to simplify the ExtJS controller code. Your error was fixed two days later, so please run `composer update` to get the latest Aimeos core and the error will be gone.

**Comment by CyberiaResurrection** [comment]
OK, thanks, that fixed that.

I retried with those details, and it looks like I'm still having problems - with setting the provider to Stripe, why is it complaining about omnipay.type being missing?

**Comment by aimeos** [comment]
Thanks for spotting this!
The check for the service provider implementation we've added interfered with the way the Omnipay/Stripe provider was handling the configuration definition. When you update the ai-payments extension, it should work as expected now.

**Comment by CyberiaResurrection** [comment]
Sorry for the delay, but yes, that seems like it's fixed it
